server:
  http_listen_port: 3100
  http_server_write_timeout: 1m
  http_server_read_timeout: 1m

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fake_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: fake_logs
          __path__: /var/log/fake/*.log
